version: '3.3'

services:
  api:
    build: .
    image: account
    ports:
      - 8080:8080
    depends_on:
      - db
    command: ["./wait-for-it.sh","db:3306", "--","./account"]
    volumes: 
      - /Users/Kylewang/go/src/account:/api
      - /Users/Kylewang/go/src/account/config/config.yml:/config.yml
  db:
    image: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
   