http:
  listenAddr: ":8080"

release:
  releaseVersion: "@RELEASE_VERSION@1.2"
  releaseTime: "@RELEASE_TIME@1.2"
  YunPianAppKey: "af2b28c3ff9f5122389f14a0ba6f2822"

database:
  url: root:root@/seed?charset=utf8&parseTime=True&loc=Local
  maxIdle: 50
  maxActive: 100
  logMode: true
