definitions:
  web.LoginParames:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  web.baseReturn:
    properties:
      code:
        type: integer
      data:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
  description: Seed-IOT
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: account api
  version: "1.0"
paths:
  /account/login:
    post:
      consumes:
      - application/json
      description: 账号密码登录
      operationId: Login
      parameters:
      - description: 用户登录
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/web.LoginParames'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/web.baseReturn'
      summary: Login
swagger: "2.0"
