definitions:
  constant.BaseReturn:
    properties:
      code:
        type: integer
      data:
        type: string
      message:
        type: string
    type: object
  web.BindDevicesParames:
    properties:
      snos:
        items:
          type: string
        type: array
      uid:
        type: string
    required:
    - snos
    - uid
    type: object
  web.GetCodeParam:
    properties:
      codeType:
        type: string
      mobile:
        type: string
    required:
    - codeType
    - mobile
    type: object
  web.LoginParames:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  web.MobileLoginParames:
    properties:
      code:
        type: string
      mobile:
        type: string
    required:
    - code
    - mobile
    type: object
info:
  contact: {}
  description: Seed-IOT
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: account api
  version: "1.0"
paths:
  /account/bindings:
    post:
      consumes:
      - application/json
      description: 绑定设备
      operationId: BindDevices
      parameters:
      - description: 用户登录
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/web.BindDevicesParames'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/constant.BaseReturn'
      summary: BindDevices
  /account/getCode:
    post:
      consumes:
      - application/json
      description: 获取验证码
      operationId: Get Code
      parameters:
      - description: 获取验证码
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/web.GetCodeParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/constant.BaseReturn'
      summary: Get Code
  /account/login:
    post:
      consumes:
      - application/json
      description: 账号密码登录
      operationId: Login
      parameters:
      - description: 用户登录
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/web.LoginParames'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/constant.BaseReturn'
      summary: Login
  /account/mobileLogin:
    post:
      consumes:
      - application/json
      description: 验证码登录
      operationId: Mobile Login
      parameters:
      - description: 用户登录
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/web.MobileLoginParames'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/constant.BaseReturn'
      summary: Mobile Login
swagger: "2.0"
